### ISSUE TITLE
Problemas no Ubuntu

### ISSUE THREAD

**Issue by hsfsesshoumaru** [GabrielZulian/pegaxy-racing-bot#4]
Não estou conseguindo fazer o bot rodar no linux, no windows funciona perfeitamente, quando tento executar no terminal dps de fazer tudo aparece as mensagens abaixo no terminal

_Traceback (most recent call last):
  File "main.py", line 169, in <module>
    main()
  File "main.py", line 106, in main
    images = load_screenshots()
  File "main.py", line 46, in load_screenshots
    targets[file.removesuffix('.png')] = cv2.imread(path)
AttributeError: 'str' object has no attribute 'removesuffix'_

obs: o bot do bomb eu consigo rodar normalmente no linux

**Comment by GabrielZulian** [comment]
Qual sua versão do python?

**Comment by hsfsesshoumaru** [comment]
> Qual sua versão do python?

Python3, a que vem padrão no ubuntu msm
